# Generated by Django 3.1.4 on 2021-02-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210221_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': ['blog_date_created']},
        ),
    ]
